-- PostgreSQL initialization script
-- This file will be executed when the PostgreSQL container starts for the first time

-- Create schemas
CREATE SCHEMA IF NOT EXISTS base;
CREATE SCHEMA IF NOT EXISTS main;

-- Grant permissions to the application user
GRANT USAGE ON SCHEMA base TO ${POSTGRES_APP_USER};
GRANT USAGE ON SCHEMA main TO ${POSTGRES_APP_USER};
GRANT CREATE ON SCHEMA base TO ${POSTGRES_APP_USER};
GRANT CREATE ON SCHEMA main TO ${POSTGRES_APP_USER};

-- Grant all privileges on future tables in schemas
ALTER DEFAULT PRIVILEGES IN SCHEMA base GRANT ALL ON TABLES TO ${POSTGRES_APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA main GRANT ALL ON TABLES TO ${POSTGRES_APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA base GRANT ALL ON SEQUENCES TO ${POSTGRES_APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA main GRANT ALL ON SEQUENCES TO ${POSTGRES_APP_USER};

-- Set search path for the user
ALTER USER ${POSTGRES_APP_USER} SET search_path = main, base, public;


-- Grant permissions on tables and views to application user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA base TO ${POSTGRES_APP_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA main TO ${POSTGRES_APP_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA base TO ${POSTGRES_APP_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA main TO ${POSTGRES_APP_USER};
GRANT SELECT ON main.active_users TO ${POSTGRES_APP_USER};

